### ISSUE TITLE
Linting should not check anything past the git cleanup scissors marker

### ISSUE THREAD

**Issue by idwagner** [joshbolduc/vscode-commitlint#593]
When using a prepare-commit-msg hook to duplicate the logic of `git commit --verbose`, The initial commit message will contain a commit diff after a special marker of `# ------------------------ >8 ------------------------`, which is stripped out of the commit message.

The extension should also honor this cleanup and ignore anything past this line.

How to reproduce:
1. Stage a git change.
2. In vscode, Click commit with empty message to bring up the commit msg in an editor
3. Paste in this content.
```
feat(core): add a thing

# On branch mybranch
# Your branch is ahead of 'origin/main' by 3 commits.
#   (use "git push" to publish your local commits)
#
# Changes to be committed:
#   (use "git restore --staged <file>..." to unstage)
#       modified:   packages/mypackage/lib/naming.ts
#
# ------------------------ >8 ------------------------
# Do not modify or remove the line above.
# Everything below it will be ignored.

This is a very long line that would fail commitlint if it were part of the body xxxxxxxxxxxxxxxxxxxxxx
```
4. Extension will report the last line failing commit lint because it is over 100 characters
5. 
Ref: https://git-scm.com/docs/git-commit#Documentation/git-commit.txt-scissors

**Comment by rcdailey** [comment]
One way to reproduce this easily is to set the gitconfig option:

```sh
git config --global commit.verbose true
```

This results in a commit message with a unified diff below the scissor marker:
![image](https://user-images.githubusercontent.com/1768054/200177648-d3dc4cbf-f62b-4c20-b768-abc50d3fffcb.png)
