### ISSUE TITLE
[FEAT] allow it to extend default configuration

### ISSUE THREAD

**Issue by yi-Xu-0100** [joshbolduc/vscode-commitlint#73]
I use the personal path for the commitlint.config.js for the open projects without the commitlint configuration.
But when I do the work in a project with the commitlint configuration setting, it will only support the personal path configuration without extends the project configuration.

Could it extend the configuration for both settings? The load functions seem to have extended options in the seed. See in [@commitlint/load](https://github.com/conventional-changelog/commitlint/blob/master/docs/reference-api.md#commitlintload). Thanks for your works!

By the way, I use the personal path for the configuration. But it works in a relative path for me.

```js
module.exports = {
	rules: {
		'body-leading-blank': [1, 'always'],
		'body-max-line-length': [2, 'always', 100],
		'footer-leading-blank': [1, 'always'],
		'footer-max-line-length': [2, 'always', 100],
		'header-max-length': [2, 'always', 100],
		'scope-case': [2, 'always', 'lower-case'],
		'subject-case': [
			2,
			'never',
			['sentence-case', 'start-case', 'pascal-case', 'upper-case'],
		],
		'subject-empty': [2, 'never'],
		'subject-full-stop': [2, 'never', '.'],
		'type-case': [2, 'always', 'lower-case'],
		'type-empty': [2, 'never'],
		'type-enum': [
			2,
			'always',
			[
				'feat',
				'fix',
				'docs',
				'perf',
				'refactor',
				'build',
				'ci',
				'revert',
				'style',
				'test',
				'chore',
			],
		],
	},
};
```
The path is `/commitlint/commitlint.config.js` to point out the `d:\commitlint\commitlint.config.js`. I want to use the later absolute path but fail. It seems only to support the relative path.

Could it read the configuration(JSON) in VS Code setting so that the configuration could sync with VS Code? There is no necessary to back up the configuration for another path. 😁

**Comment by yi-Xu-0100** [comment]
@joshbolduc  I misunderstand the configuration, so I add a new option to allow it to extend a default configuration. 😀

**Comment by joshbolduc** [comment]
> The path is `/commitlint/commitlint.config.js` to point out the `d:\commitlint\commitlint.config.js`. I want to use the later absolute path but fail. It seems only to support the relative path.

This sounds like a bug, would you mind opening another issue for that if it's still happening?

> Could it read the configuration(JSON) in VS Code setting so that the configuration could sync with VS Code? There is no necessary to back up the configuration for another path. 😁

That sounds like a good idea, if you'd like to open an issue for this too. I just don't want them to get lost when this issue gets closed. Thanks!
